# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_MuscleBloodFlowControl.

Source: biomodels_ebi:MODEL0911202318
Original: https://www.ebi.ac.uk/biomodels/MODEL0911202318
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Musclebloodflowcontrol(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_MuscleBloodFlowControl."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911202318'
    _TITLE = 'Guyton1972_MuscleBloodFlowControl'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'muscle_oxygen': ('PMO',
                       38.0666,
                       'dimensionless',
                       'Sets muscle oxygen for the simulation scenario. Default `38.0666`.')}
    _OBSERVABLES = ['AMM', 'AMM1', 'AMM2', 'AMM4']
    _SPECIES_LABELS = {'AMM': 'AMM', 'AMM1': 'AMM1', 'AMM2': 'AMM2', 'AMM4': 'AMM4'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911202318.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972MusclebloodflowcontrolModel0911202318Model = SbmlGuyton1972Musclebloodflowcontrol
