# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Clancy2001_Kchannel.

Source: biomodels_ebi:BIOMD0000000121
Original: https://www.ebi.ac.uk/biomodels/BIOMD0000000121
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlClancy2001Kchannel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Clancy2001_Kchannel."""

    _OBSERVABLE_STRATEGY = 'species'
    _SBML_ID = 'BIOMD0000000121'
    _TITLE = 'Clancy2001_Kchannel'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'temperature': ('Temp',
                     310.0,
                     'dimensionless',
                     'Sets temperature for the simulation scenario. Default `310.0`.'),
     'extracellular_potassium': ('ko',
                                 5.4,
                                 'mM',
                                 'Sets extracellular potassium for the simulation scenario. '
                                 'Default `5.4`.'),
     'intracellular_potassium': ('ki',
                                 140.0,
                                 'mM',
                                 'Sets intracellular potassium for the simulation scenario. '
                                 'Default `140.0`.'),
     'holding_voltage': ('vhold',
                         -40.0,
                         'mV',
                         'Sets holding voltage for the simulation scenario. Default `-40.0`.'),
     'test_voltage': ('vtest',
                      0.0,
                      'mV',
                      'Sets test voltage for the simulation scenario. Default `0.0`.')}
    _OBSERVABLES = ['c3', 'c2', 'c1', 'o', 'i', 'ik']
    _SPECIES_LABELS = {'c3': 'ClosedState_3',
     'c2': 'ClosedState_2',
     'c1': 'ClosedState_1',
     'o': 'OpenState',
     'i': 'InactivationState',
     'ik': 'cardiac delayed rectifier current'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/BIOMD0000000121.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Clancy2001KchannelBiomd0000000121Model = SbmlClancy2001Kchannel
