# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_HeartHypertrophy.

Source: biomodels_ebi:MODEL0911231713
Original: https://www.ebi.ac.uk/biomodels/MODEL0911231713
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Hearthypertrophy(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_HeartHypertrophy."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911231713'
    _TITLE = 'Guyton1972_HeartHypertrophy'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'aortic_flow': ('QAO',
                     5.00707,
                     'dimensionless',
                     'Sets aortic flow for the simulation scenario. Default `5.00707`.'),
     'arterial_pressure': ('PA',
                           103.525,
                           'dimensionless',
                           'Sets arterial pressure for the simulation scenario. Default '
                           '`103.525`.'),
     'pulmonary_artery_pressure': ('PPA',
                                   15.6376,
                                   'dimensionless',
                                   'Sets pulmonary artery pressure for the simulation scenario. '
                                   'Default `15.6376`.')}
    _OBSERVABLES = ['HSL', 'HSR', 'HMD']
    _SPECIES_LABELS = {'HSL': 'HSL', 'HSR': 'HSR', 'HMD': 'HMD'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911231713.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972HearthypertrophyModel0911231713Model = SbmlGuyton1972Hearthypertrophy
