# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_ThirstDrinking_SaltAppetite.

Source: biomodels_ebi:MODEL0910846879
Original: https://www.ebi.ac.uk/biomodels/MODEL0910846879
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972ThirstdrinkingSaltappetite(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_ThirstDrinking_SaltAppetite."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0910846879'
    _TITLE = 'Guyton1972_ThirstDrinking_SaltAppetite'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'antidiuretic_hormone_concentration': ('ADHC',
                                            1.0,
                                            'dimensionless',
                                            'Sets antidiuretic hormone concentration for the '
                                            'simulation scenario. Default `1.0`.'),
     'angiotensin_drive': ('ANM',
                           0.987545,
                           'dimensionless',
                           'Sets angiotensin drive for the simulation scenario. Default '
                           '`0.987545`.'),
     'arterial_pressure': ('POT',
                           35.1148,
                           'dimensionless',
                           'Sets arterial pressure for the simulation scenario. Default '
                           '`35.1148`.')}
    _OBSERVABLES = ['TVD', 'AHTH', 'AHTH1', 'TVZ']
    _SPECIES_LABELS = {'TVD': 'TVD', 'AHTH': 'AHTH', 'AHTH1': 'AHTH1', 'TVZ': 'TVZ'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0910846879.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972ThirstdrinkingSaltappetiteModel0910846879Model = SbmlGuyton1972ThirstdrinkingSaltappetite
