# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_Electrolytes.

Source: biomodels_ebi:MODEL0912160001
Original: https://www.ebi.ac.uk/biomodels/MODEL0912160001
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Electrolytes(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_Electrolytes."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0912160001'
    _TITLE = 'Guyton1972_Electrolytes'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'sodium_intake': ('NID',
                       0.1,
                       'dimensionless',
                       'Sets sodium intake for the simulation scenario. Default `0.1`.'),
     'potassium_intake': ('KID',
                          0.08,
                          'dimensionless',
                          'Sets potassium intake for the simulation scenario. Default `0.08`.'),
     'aldosterone_drive': ('AMK',
                           1.037,
                           'dimensionless',
                           'Sets aldosterone drive for the simulation scenario. Default `1.037`.')}
    _OBSERVABLES = ['NAE', 'KE', 'KTOT', 'NED', 'KOD']
    _SPECIES_LABELS = {'NAE': 'NAE', 'KE': 'KE', 'KTOT': 'KTOT', 'NED': 'NED', 'KOD': 'KOD'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0912160001.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972ElectrolytesModel0912160001Model = SbmlGuyton1972Electrolytes
