# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_HeartRateStrokeVolume.

Source: biomodels_ebi:MODEL0911270006
Original: https://www.ebi.ac.uk/biomodels/MODEL0911270006
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Heartratestrokevolume(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_HeartRateStrokeVolume."""

    _OBSERVABLE_STRATEGY = 'assignmentRule'
    _SBML_ID = 'MODEL0911270006'
    _TITLE = 'Guyton1972_HeartRateStrokeVolume'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'autonomic_drive': ('AUR',
                         1.3,
                         'dimensionless',
                         'Sets autonomic drive for the simulation scenario. Default `1.3`.'),
     'right_atrial_pressure': ('PRA',
                               0.00852183,
                               'dimensionless',
                               'Sets right atrial pressure for the simulation scenario. Default '
                               '`0.00852183`.'),
     'cardiac_output': ('QLO',
                        4.9943,
                        'dimensionless',
                        'Sets cardiac output for the simulation scenario. Default `4.9943`.')}
    _OBSERVABLES = ['HR', 'SVO', 'AUHR', 'PRHR', 'HDHR']
    _SPECIES_LABELS = {'HR': 'HR', 'SVO': 'SVO', 'AUHR': 'AUHR', 'PRHR': 'PRHR', 'HDHR': 'HDHR'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911270006.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972HeartratestrokevolumeModel0911270006Model = SbmlGuyton1972Heartratestrokevolume
