# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Niederer2006_CardiacMyocyteRelaxation.

Source: biomodels_ebi:MODEL8687196544
Original: https://www.ebi.ac.uk/biomodels/MODEL8687196544
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlNiederer2006Cardiacmyocyterelaxation(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Niederer2006_CardiacMyocyteRelaxation."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL8687196544'
    _TITLE = 'Niederer2006_CardiacMyocyteRelaxation'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'troponin_pool': ('TRPN',
                       0.067593139865,
                       'dimensionless',
                       'Sets troponin pool for the simulation scenario. Default `0.067593139865`.'),
     'relaxation_rate': ('alpha_r1',
                         0.002,
                         'dimensionless',
                         'Sets relaxation rate for the simulation scenario. Default `0.002`.'),
     'cooperativity': ('alpha_0',
                       0.008,
                       'dimensionless',
                       'Sets cooperativity for the simulation scenario. Default `0.008`.')}
    _OBSERVABLES = ['Ca_i', 'Ca_b', 'TRPN', 'z']
    _SPECIES_LABELS = {'Ca_i': 'Ca_i', 'Ca_b': 'Ca_b', 'TRPN': 'TRPN', 'z': 'z'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL8687196544.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Niederer2006CardiacmyocyterelaxationModel8687196544Model = SbmlNiederer2006Cardiacmyocyterelaxation
