# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_AtrialNatriureticPeptide.

Source: biomodels_ebi:MODEL0911272039
Original: https://www.ebi.ac.uk/biomodels/MODEL0911272039
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Atrialnatriureticpeptide(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_AtrialNatriureticPeptide."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911272039'
    _TITLE = 'Guyton1972_AtrialNatriureticPeptide'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'left_atrial_pressure': ('PLA',
                              2.0,
                              'dimensionless',
                              'Sets left atrial pressure for the simulation scenario. Default '
                              '`2.0`.'),
     'right_atrial_pressure': ('PRA',
                               0.00852183,
                               'dimensionless',
                               'Sets right atrial pressure for the simulation scenario. Default '
                               '`0.00852183`.'),
     'atrial_natriuretic_peptide_infusion': ('ANPINF',
                                             0.0,
                                             'dimensionless',
                                             'Sets atrial natriuretic peptide infusion for the '
                                             'simulation scenario. Default `0.0`.')}
    _OBSERVABLES = ['ANP', 'ANPL', 'ANPC', 'ANPX']
    _SPECIES_LABELS = {'ANP': 'ANP', 'ANPL': 'ANPL', 'ANPC': 'ANPC', 'ANPX': 'ANPX'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911272039.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972AtrialnatriureticpeptideModel0911272039Model = SbmlGuyton1972Atrialnatriureticpeptide
