# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Pasek2006_VentricularCardioMyocytes.

Source: biomodels_ebi:MODEL0406553884
Original: https://www.ebi.ac.uk/biomodels/MODEL0406553884
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlPasek2006Ventricularcardiomyocytes(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Pasek2006_VentricularCardioMyocytes."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0406553884'
    _TITLE = 'Pasek2006_VentricularCardioMyocytes'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'extracellular_sodium': ('Nae',
                              140.0,
                              'mM',
                              'Sets extracellular sodium for the simulation scenario. Default '
                              '`140.0`.'),
     'extracellular_potassium': ('Ke',
                                 5.4,
                                 'mM',
                                 'Sets extracellular potassium for the simulation scenario. '
                                 'Default `5.4`.'),
     'extracellular_calcium': ('Cae',
                               1.2,
                               'mM',
                               'Sets extracellular calcium for the simulation scenario. Default '
                               '`1.2`.'),
     'temperature': ('T',
                     295.0,
                     'dimensionless',
                     'Sets temperature for the simulation scenario. Default `295.0`.')}
    _OBSERVABLES = ['Vt', 'Vd', 'Cms', 'Cmt']
    _SPECIES_LABELS = {'Vt': 'Vt', 'Vd': 'Vd', 'Cms': 'Cms', 'Cmt': 'Cmt'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0406553884.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Pasek2006VentricularcardiomyocytesModel0406553884Model = SbmlPasek2006Ventricularcardiomyocytes
