# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_Angiotensin.

Source: biomodels_ebi:MODEL0911342562
Original: https://www.ebi.ac.uk/biomodels/MODEL0911342562
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Angiotensin(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_Angiotensin."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911342562'
    _TITLE = 'Guyton1972_Angiotensin'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'renal_perfusion': ('MDFLW',
                         1.00051,
                         'dimensionless',
                         'Sets renal perfusion for the simulation scenario. Default `1.00051`.'),
     'sympathetic_drive': ('ANCSNS',
                           0.4,
                           'dimensionless',
                           'Sets sympathetic drive for the simulation scenario. Default `0.4`.'),
     'angiotensin_infusion': ('ANGINF',
                              0.0,
                              'dimensionless',
                              'Sets angiotensin infusion for the simulation scenario. Default '
                              '`0.0`.')}
    _OBSERVABLES = ['ANC', 'ANT', 'ANM', 'ANU', 'ANV', 'ANPR']
    _SPECIES_LABELS = {'ANC': 'ANC', 'ANT': 'ANT', 'ANM': 'ANM', 'ANU': 'ANU', 'ANV': 'ANV', 'ANPR': 'ANPR'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911342562.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972AngiotensinModel0911342562Model = SbmlGuyton1972Angiotensin
