# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_Aldosterone.

Source: biomodels_ebi:MODEL0911376350
Original: https://www.ebi.ac.uk/biomodels/MODEL0911376350
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Aldosterone(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_Aldosterone."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911376350'
    _TITLE = 'Guyton1972_Aldosterone'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'angiotensin_drive': ('ANM',
                           0.987545,
                           'dimensionless',
                           'Sets angiotensin drive for the simulation scenario. Default '
                           '`0.987545`.'),
     'potassium_effect': ('CKE',
                          4.44092,
                          'dimensionless',
                          'Sets potassium effect for the simulation scenario. Default `4.44092`.'),
     'sympathetic_drive': ('AMCSNS',
                           0.65,
                           'dimensionless',
                           'Sets sympathetic drive for the simulation scenario. Default `0.65`.')}
    _OBSERVABLES = ['AMR', 'AM', 'AMC', 'AMK']
    _SPECIES_LABELS = {'AMR': 'AMR', 'AM': 'AM', 'AMC': 'AMC', 'AMK': 'AMK'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911376350.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972AldosteroneModel0911376350Model = SbmlGuyton1972Aldosterone
