# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_AntidiureticHormone.

Source: biomodels_ebi:MODEL0911309080
Original: https://www.ebi.ac.uk/biomodels/MODEL0911309080
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Antidiuretichormone(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_AntidiureticHormone."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911309080'
    _TITLE = 'Guyton1972_AntidiureticHormone'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'sodium_concentration': ('CNA',
                              142.035,
                              'dimensionless',
                              'Sets sodium concentration for the simulation scenario. Default '
                              '`142.035`.'),
     'arterial_pressure': ('PA1',
                           103.525,
                           'dimensionless',
                           'Sets arterial pressure for the simulation scenario. Default '
                           '`103.525`.'),
     'antidiuretic_hormone_infusion': ('ADHINF',
                                       0.0,
                                       'dimensionless',
                                       'Sets antidiuretic hormone infusion for the simulation '
                                       'scenario. Default `0.0`.')}
    _OBSERVABLES = ['ADH', 'ADHC', 'ADHMV', 'ADHMK']
    _SPECIES_LABELS = {'ADH': 'ADH', 'ADHC': 'ADHC', 'ADHMV': 'ADHMV', 'ADHMK': 'ADHMK'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911309080.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972AntidiuretichormoneModel0911309080Model = SbmlGuyton1972Antidiuretichormone
