# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Chen2007_NeuronalEndothelialNOS.

Source: biomodels_ebi:MODEL0491251823
Original: https://www.ebi.ac.uk/biomodels/MODEL0491251823
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlChen2007Neuronalendothelialnos(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Chen2007_NeuronalEndothelialNOS."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0491251823'
    _TITLE = 'Chen2007_NeuronalEndothelialNOS'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'l_arginine': ('Fe3_Arg',
                    0.0,
                    'dimensionless',
                    'Sets L-arginine for the simulation scenario. Default `0.0`.'),
     'oxygen': ('Fe3_O2_Arg',
                0.0,
                'dimensionless',
                'Sets oxygen for the simulation scenario. Default `0.0`.'),
     'nitric_oxide_synthase_pool': ('Fe3',
                                    0.3,
                                    'dimensionless',
                                    'Sets nitric oxide synthase pool for the simulation scenario. '
                                    'Default `0.3`.')}
    _OBSERVABLES = ['NO', 'citrulline', 'Fe3', 'Fe2', 'Fe3_Arg', 'Fe2_Arg', 'Fe3_NOHA', 'Fe3_NO']
    _SPECIES_LABELS = {'NO': 'NO',
     'citrulline': 'citrulline',
     'Fe3': 'Fe3',
     'Fe2': 'Fe2',
     'Fe3_Arg': 'Fe3_Arg',
     'Fe2_Arg': 'Fe2_Arg',
     'Fe3_NOHA': 'Fe3_NOHA',
     'Fe3_NO': 'Fe3_NO'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0491251823.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Chen2007NeuronalendothelialnosModel0491251823Model = SbmlChen2007Neuronalendothelialnos
