# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_NonMuscleBloodFlowControl.

Source: biomodels_ebi:MODEL0911169699
Original: https://www.ebi.ac.uk/biomodels/MODEL0911169699
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Nonmusclebloodflowcontrol(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_NonMuscleBloodFlowControl."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911169699'
    _TITLE = 'Guyton1972_NonMuscleBloodFlowControl'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'tissue_oxygen': ('POT',
                       35.1148,
                       'dimensionless',
                       'Sets tissue oxygen for the simulation scenario. Default `35.1148`.'),
     'autonomic_drive': ('AUTOSN',
                         0.9,
                         'dimensionless',
                         'Sets autonomic drive for the simulation scenario. Default `0.9`.')}
    _OBSERVABLES = ['AR1', 'AR2', 'AR3', 'ARM', 'ARM1']
    _SPECIES_LABELS = {'AR1': 'AR1', 'AR2': 'AR2', 'AR3': 'AR3', 'ARM': 'ARM', 'ARM1': 'ARM1'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911169699.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972NonmusclebloodflowcontrolModel0911169699Model = SbmlGuyton1972Nonmusclebloodflowcontrol
