# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_PulmonaryFluidDynamics.

Source: biomodels_ebi:MODEL0911091440
Original: https://www.ebi.ac.uk/biomodels/MODEL0911091440
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Pulmonaryfluiddynamics(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_PulmonaryFluidDynamics."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911091440'
    _TITLE = 'Guyton1972_PulmonaryFluidDynamics'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'capillary_pressure': ('PPC',
                            29.9941,
                            'dimensionless',
                            'Sets capillary pressure for the simulation scenario. Default '
                            '`29.9941`.'),
     'plasma_oncotic_pressure': ('CPP',
                                 71.9719,
                                 'dimensionless',
                                 'Sets plasma oncotic pressure for the simulation scenario. '
                                 'Default `71.9719`.')}
    _OBSERVABLES = ['VPF', 'PPI', 'PFI', 'PLF']
    _SPECIES_LABELS = {'VPF': 'VPF', 'PPI': 'PPI', 'PFI': 'PFI', 'PLF': 'PLF'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911091440.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972PulmonaryfluiddynamicsModel0911091440Model = SbmlGuyton1972Pulmonaryfluiddynamics
