# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Chen2006 - Nitric Oxide Release from Endothelial Cells.

Source: biomodels_ebi:BIOMD0000000676
Original: https://www.ebi.ac.uk/biomodels/BIOMD0000000676
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlChen2006NitricOxideReleaseFromEndothelialCells(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Chen2006 - Nitric Oxide Release from Endothelial Cells."""

    _OBSERVABLE_STRATEGY = 'species'
    _SBML_ID = 'BIOMD0000000676'
    _TITLE = 'Chen2006 - Nitric Oxide Release from Endothelial Cells'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'l_arginine': ('Arg',
                    100.0,
                    'dimensionless',
                    'Sets L-arginine for the simulation scenario. Default `100`.'),
     'oxygen': ('O2',
                150.0,
                'dimensionless',
                'Sets oxygen for the simulation scenario. Default `150`.'),
     'nitric_oxide_synthase_pool': ('Fe3__enos',
                                    0.015,
                                    'dimensionless',
                                    'Sets nitric oxide synthase pool for the simulation scenario. '
                                    'Default `0.015`.'),
     'arg_binding_rate': ('k1',
                          0.1,
                          'dimensionless',
                          'Sets arg binding rate for the simulation scenario. Default `0.1`.'),
     'oxygen_binding_rate': ('k4',
                             1.89,
                             'dimensionless',
                             'Sets oxygen binding rate for the simulation scenario. Default '
                             '`1.89`.')}
    _OBSERVABLES = ['NO', 'Citrulline', 'Arg', 'Fe3__enos', 'O2', 'Fe3__Arg', 'Fe3__NO']
    _SPECIES_LABELS = {'Arg': 'Arg',
     'Fe3__enos': 'Fe3+(enos)',
     'Fe3__Arg': 'Fe3+_Arg',
     'Fe2': 'Fe2+',
     'Fe2__Arg': 'Fe2+_Arg',
     'Fe3__NO': 'Fe3+_NO',
     'NO': 'NO',
     'Fe2__NO': 'Fe2+_NO',
     'Fe3__NOHA': 'Fe3+_NOHA',
     'NOHA': 'NOHA',
     'Fe2__NOHA': 'Fe2+_NOHA',
     'O2': 'O2',
     'Fe3__O2__Arg': 'Fe3+_O2-_Arg',
     'Fe3__O2__NOHA': 'Fe3+_O2-_NOHA',
     'Citrulline': 'Citrulline'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/BIOMD0000000676.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Chen2006NitricOxideReleaseFromEndothelialCBiomd0000000676Model = SbmlChen2006NitricOxideReleaseFromEndothelialCells
