# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_RedCells_Viscosity.

Source: biomodels_ebi:MODEL0910928451
Original: https://www.ebi.ac.uk/biomodels/MODEL0910928451
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972RedcellsViscosity(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_RedCells_Viscosity."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0910928451'
    _TITLE = 'Guyton1972_RedCells_Viscosity'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'plasma_volume': ('VP',
                       3.00449,
                       'dimensionless',
                       'Sets plasma volume for the simulation scenario. Default `3.00449`.'),
     'erythropoiesis_drive': ('PO2AMB',
                              150.0,
                              'dimensionless',
                              'Sets erythropoiesis drive for the simulation scenario. Default '
                              '`150.0`.')}
    _OBSERVABLES = ['VRC', 'VB', 'HM', 'VIM']
    _SPECIES_LABELS = {'VRC': 'VRC', 'VB': 'VB', 'HM': 'HM', 'VIM': 'VIM'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0910928451.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972RedcellsViscosityModel0910928451Model = SbmlGuyton1972RedcellsViscosity
