# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_CapillaryDynamics.

Source: biomodels_ebi:MODEL0912160000
Original: https://www.ebi.ac.uk/biomodels/MODEL0912160000
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Capillarydynamics(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_CapillaryDynamics."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0912160000'
    _TITLE = 'Guyton1972_CapillaryDynamics'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'capillary_pressure': ('PC',
                            16.9144,
                            'dimensionless',
                            'Sets capillary pressure for the simulation scenario. Default '
                            '`16.9144`.'),
     'filtration_coefficient': ('DFP',
                                -4.078e-07,
                                'dimensionless',
                                'Sets filtration coefficient for the simulation scenario. Default '
                                '`-4.078e-07`.')}
    _OBSERVABLES = ['VTC', 'VPF', 'VEC', 'BFN']
    _SPECIES_LABELS = {'VTC': 'VTC', 'VPF': 'VPF', 'VEC': 'VEC', 'BFN': 'BFN'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0912160000.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972CapillarydynamicsModel0912160000Model = SbmlGuyton1972Capillarydynamics
