# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_PulmonaryOxygenIntake.

Source: biomodels_ebi:MODEL0911047946
Original: https://www.ebi.ac.uk/biomodels/MODEL0911047946
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Pulmonaryoxygenintake(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_PulmonaryOxygenIntake."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911047946'
    _TITLE = 'Guyton1972_PulmonaryOxygenIntake'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'pulmonary_blood_flow': ('QRO',
                              4.97838,
                              'dimensionless',
                              'Sets pulmonary blood flow for the simulation scenario. Default '
                              '`4.97838`.'),
     'oxygen_demand': ('RMO',
                       56.8057,
                       'dimensionless',
                       'Sets oxygen demand for the simulation scenario. Default `56.8057`.'),
     'ambient_oxygen': ('PO2AMB',
                        150.0,
                        'dimensionless',
                        'Sets ambient oxygen for the simulation scenario. Default `150.0`.')}
    _OBSERVABLES = ['PO2ALV', 'PO2ART', 'OSA', 'OVA']
    _SPECIES_LABELS = {'PO2ALV': 'PO2ALV', 'PO2ART': 'PO2ART', 'OSA': 'OSA', 'OVA': 'OVA'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911047946.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972PulmonaryoxygenintakeModel0911047946Model = SbmlGuyton1972Pulmonaryoxygenintake
