# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Iyer2007_Arrhythmia_CardiacDeath.

Source: biomodels_ebi:MODEL1006230030
Original: https://www.ebi.ac.uk/biomodels/MODEL1006230030
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlIyer2007ArrhythmiaCardiacdeath(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Iyer2007_Arrhythmia_CardiacDeath."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL1006230030'
    _TITLE = 'Iyer2007_Arrhythmia_CardiacDeath'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'temperature': ('Temp',
                     310.0,
                     'dimensionless',
                     'Sets temperature for the simulation scenario. Default `310.0`.'),
     'isoproterenol_drive': ('iso',
                             0.0,
                             'dimensionless',
                             'Sets isoproterenol drive for the simulation scenario. Default '
                             '`0.0`.'),
     'calsequestrin_buffer': ('CSQN2',
                              0.0,
                              'dimensionless',
                              'Sets calsequestrin buffer for the simulation scenario. Default '
                              '`0.0`.'),
     'ryanodine_receptor_pool': ('RyR2',
                                 0.0,
                                 'dimensionless',
                                 'Sets ryanodine receptor pool for the simulation scenario. '
                                 'Default `0.0`.'),
     'intracellular_calcium': ('Cai',
                               0.00036396867218,
                               'mM',
                               'Sets intracellular calcium for the simulation scenario. Default '
                               '`0.00036396867218`.')}
    _OBSERVABLES = ['V', 'Cai', 'CaSS', 'CaJSR', 'CaNSR', 'Nai', 'Ki', 'i_tot']
    _SPECIES_LABELS = {'V': 'V',
     'Cai': 'Cai',
     'CaSS': 'CaSS',
     'CaJSR': 'CaJSR',
     'CaNSR': 'CaNSR',
     'Nai': 'Nai',
     'Ki': 'Ki',
     'i_tot': 'i_tot'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL1006230030.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Iyer2007ArrhythmiaCardiacdeathModel1006230030Model = SbmlIyer2007ArrhythmiaCardiacdeath
