# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_volumeReceptors.

Source: biomodels_ebi:MODEL0909931851
Original: https://www.ebi.ac.uk/biomodels/MODEL0909931851
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Volumereceptors(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_volumeReceptors."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0909931851'
    _TITLE = 'Guyton1972_volumeReceptors'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'right_atrial_pressure': ('PRA',
                               0.00852183,
                               'dimensionless',
                               'Sets right atrial pressure for the simulation scenario. Default '
                               '`0.00852183`.')}
    _OBSERVABLES = ['AHZ', 'AHY', 'ATRRFB', 'ATRVFB', 'ATRFBM', 'ATRVM']
    _SPECIES_LABELS = {'AHZ': 'AHZ',
     'AHY': 'AHY',
     'ATRRFB': 'ATRRFB',
     'ATRVFB': 'ATRVFB',
     'ATRFBM': 'ATRFBM',
     'ATRVM': 'ATRVM'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0909931851.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972VolumereceptorsModel0909931851Model = SbmlGuyton1972Volumereceptors
