# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Iyer2004_VentricularMyocyte.

Source: biomodels_ebi:MODEL0847999575
Original: https://www.ebi.ac.uk/biomodels/MODEL0847999575
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlIyer2004Ventricularmyocyte(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Iyer2004_VentricularMyocyte."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0847999575'
    _TITLE = 'Iyer2004_VentricularMyocyte'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'temperature': ('Temp',
                     310.0,
                     'dimensionless',
                     'Sets temperature for the simulation scenario. Default `310.0`.'),
     'extracellular_sodium': ('Nai',
                              9.798304162,
                              'mM',
                              'Sets extracellular sodium for the simulation scenario. Default '
                              '`9.798304162`.'),
     'extracellular_potassium': ('Ki',
                                 125.5589432,
                                 'mM',
                                 'Sets extracellular potassium for the simulation scenario. '
                                 'Default `125.5589432`.'),
     'intracellular_calcium': ('Cai',
                               8.601192016e-05,
                               'mM',
                               'Sets intracellular calcium for the simulation scenario. Default '
                               '`8.601192016e-05`.')}
    _OBSERVABLES = ['V', 'Cai', 'Nai', 'Ki', 'CaSS', 'CaJSR', 'CaNSR', 'i_tot']
    _SPECIES_LABELS = {'V': 'V',
     'Cai': 'Cai',
     'Nai': 'Nai',
     'Ki': 'Ki',
     'CaSS': 'CaSS',
     'CaJSR': 'CaJSR',
     'CaNSR': 'CaNSR',
     'i_tot': 'i_tot'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0847999575.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Iyer2004VentricularmyocyteModel0847999575Model = SbmlIyer2004Ventricularmyocyte
