# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_StressRelaxation.

Source: biomodels_ebi:MODEL0910896131
Original: https://www.ebi.ac.uk/biomodels/MODEL0910896131
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Stressrelaxation(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_StressRelaxation."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0910896131'
    _TITLE = 'Guyton1972_StressRelaxation'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'effective_volume': ('VVE',
                          0.743224,
                          'dimensionless',
                          'Sets effective volume for the simulation scenario. Default `0.743224`.'),
     'stress_relaxation_gain': ('SRK',
                                5.0,
                                'dimensionless',
                                'Sets stress relaxation gain for the simulation scenario. Default '
                                '`5.0`.'),
     'stress_relaxation_gain_2': ('SRK2',
                                  10000.0,
                                  'dimensionless',
                                  'Sets stress relaxation gain 2 for the simulation scenario. '
                                  'Default `10000.0`.')}
    _OBSERVABLES = ['SR', 'SR2', 'VV6', 'VV7']
    _SPECIES_LABELS = {'SR': 'SR', 'SR2': 'SR2', 'VV6': 'VV6', 'VV7': 'VV7'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0910896131.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972StressrelaxationModel0910896131Model = SbmlGuyton1972Stressrelaxation
