# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Guyton1972_Autonomics.

Source: biomodels_ebi:MODEL0911270005
Original: https://www.ebi.ac.uk/biomodels/MODEL0911270005
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlGuyton1972Autonomics(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Guyton1972_Autonomics."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0911270005'
    _TITLE = 'Guyton1972_Autonomics'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'arterial_pressure': ('PA',
                           103.525,
                           'dimensionless',
                           'Sets arterial pressure for the simulation scenario. Default '
                           '`103.525`.'),
     'arterial_oxygen': ('PO2ART',
                         97.0439,
                         'dimensionless',
                         'Sets arterial oxygen for the simulation scenario. Default `97.0439`.'),
     'left_atrial_pressure': ('PLA',
                              2.0,
                              'dimensionless',
                              'Sets left atrial pressure for the simulation scenario. Default '
                              '`2.0`.'),
     'right_atrial_pressure': ('PRA',
                               0.00852183,
                               'dimensionless',
                               'Sets right atrial pressure for the simulation scenario. Default '
                               '`0.00852183`.')}
    _OBSERVABLES = ['AUC', 'AU6C', 'AUC2', 'AUC3']
    _SPECIES_LABELS = {'AUC': 'AUC', 'AU6C': 'AU6C', 'AUC2': 'AUC2', 'AUC3': 'AUC3'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0911270005.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Guyton1972AutonomicsModel0911270005Model = SbmlGuyton1972Autonomics
