# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Cooling2007_IP3transients_CardiacMyocyte.

Source: biomodels_ebi:BIOMD0000000400
Original: https://www.ebi.ac.uk/biomodels/BIOMD0000000400
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlCooling2007Ip3transientsCardiacmyocyte(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Cooling2007_IP3transients_CardiacMyocyte."""

    _OBSERVABLE_STRATEGY = 'species'
    _SBML_ID = 'BIOMD0000000400'
    _TITLE = 'Cooling2007_IP3transients_CardiacMyocyte'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'inositol_trisphosphate_initial': ('IP3',
                                        0.015,
                                        'dimensionless',
                                        'Sets inositol trisphosphate initial for the simulation '
                                        'scenario. Default `0.015`.'),
     'calcium_initial': ('Ca',
                         0.1,
                         'dimensionless',
                         'Sets calcium initial for the simulation scenario. Default `0.1`.'),
     'receptor_initial': ('R',
                          13.9,
                          'dimensionless',
                          'Sets receptor initial for the simulation scenario. Default `13.9`.')}
    _OBSERVABLES = ['Ca', 'IP3', 'R', 'Rl', 'Rg', 'Rlg', 'Pc', 'Pcg']
    _SPECIES_LABELS = {'Gd': 'Gd',
     'Gt': 'Gt',
     'R': 'R',
     'Rl': 'Rl',
     'Rg': 'Rg',
     'Rlg': 'Rlg',
     'Rlgp': 'Rlgp',
     'IP3': 'IP3',
     'Pc': 'Pc',
     'Pcg': 'Pcg',
     'P': 'P',
     'Pg': 'Pg',
     'Ca': 'Ca'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/BIOMD0000000400.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Cooling2007Ip3transientsCardiacmyocyteBiomd0000000400Model = SbmlCooling2007Ip3transientsCardiacmyocyte
