# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Karlstaedt2019 - G6P accumulation via Phosphoglucose isomerase inhibition in heart muscles.

Source: biomodels_ebi:MODEL1910170001
Original: https://www.ebi.ac.uk/biomodels/MODEL1910170001
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlKarlstaedt2019G6pAccumulationViaPhosphoglucose(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Karlstaedt2019 - G6P accumulation via Phosphoglucose isomerase inhibition in heart muscles."""

    _OBSERVABLE_STRATEGY = 'species'
    _SBML_ID = 'MODEL1910170001'
    _TITLE = 'Karlstaedt2019 - G6P accumulation via Phosphoglucose isomerase inhibition in heart muscles'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'extracellular_glucose': ('GLCo',
                               5.5,
                               'dimensionless',
                               'Sets extracellular glucose for the simulation scenario. Default '
                               '`5.5`.'),
     'cellular_energy_pool': ('ATP',
                              3.0417,
                              'dimensionless',
                              'Sets cellular energy pool for the simulation scenario. Default '
                              '`3.0417`.')}
    _OBSERVABLES = ['GLCo', 'GLCi', 'G6P', 'F6P', 'F16bP', 'GAP', 'PEP', 'PYR']
    _SPECIES_LABELS = {'GLCo': 'Glc(ext)',
     'GLCi': 'Glc(int)',
     'ATP': 'ATP',
     'G6P': 'G6P',
     'ADP': 'ADP',
     'F6P': 'F6P',
     'F16bP': 'Fru1,6-P2',
     'AMP': 'AMP',
     'F26bP': 'Fru2,6-P2',
     'DHAP': 'DHAP',
     'GAP': 'G3P',
     'NAD': 'NAD',
     'BPG': 'BPG',
     'NADH': 'NADH',
     'P3G': 'P3G',
     'P2G': 'P2G',
     'PEP': 'PEP',
     'PYR': 'Pyr',
     'AcAld': 'Lac',
     'CO2': 'CO2',
     'Glycerol': 'glycerol',
     'Glycogen': 'glycogen',
     'Succinate': 'Lac(ext)'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL1910170001.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Karlstaedt2019G6pAccumulationViaPhosphoglucoModel1910170001Model = SbmlKarlstaedt2019G6pAccumulationViaPhosphoglucose
