# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Irvine1999_CardiacSodiumChannel.

Source: biomodels_ebi:MODEL0848062679
Original: https://www.ebi.ac.uk/biomodels/MODEL0848062679
"""
from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class SbmlIrvine1999Cardiacsodiumchannel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Irvine1999_CardiacSodiumChannel."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _SBML_ID = 'MODEL0848062679'
    _TITLE = 'Irvine1999_CardiacSodiumChannel'
    _TIME_UNIT = 's'
    _PARAMETER_INPUTS = {'holding_voltage': ('V',
                         -0.12,
                         'mV',
                         'Sets holding voltage for the simulation scenario. Default `-0.12`.'),
     'sodium_reversal_voltage': ('E_Na',
                                 0.044675,
                                 'mV',
                                 'Sets sodium reversal voltage for the simulation scenario. '
                                 'Default `0.044675`.'),
     'sodium_conductance': ('g_Na',
                            0.0131,
                            'mS_per_uF',
                            'Sets sodium conductance for the simulation scenario. Default '
                            '`0.0131`.')}
    _OBSERVABLES = ['O1', 'O2', 'C0', 'C1', 'C2', 'C3', 'C4', 'I', 'P_open']
    _SPECIES_LABELS = {'O1': 'O1',
     'O2': 'O2',
     'C0': 'C0',
     'C1': 'C1',
     'C2': 'C2',
     'C3': 'C3',
     'C4': 'C4',
     'I': 'I',
     'P_open': 'P_open'}
    _ENABLE_PARAMETER_OVERRIDES = True
    _ENABLE_INITIAL_CONDITIONS = True
    _STATE_OUTPUT_AS_PAYLOAD = True
    _SPECIES_LABELS_OUTPUT_AS_PAYLOAD = True

    def __init__(
        self,
        model_path: str = 'data/MODEL0848062679.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)


# Canonical alias for stable entrypoint naming.
Irvine1999CardiacsodiumchannelModel0848062679Model = SbmlIrvine1999Cardiacsodiumchannel
